Repository JuliaCI/julia-buildkite, pull requests merged in 2024-08, with the labels that each got.

#376 update stdlib pkgimage checksums for windows
  pipelines/main/launch_signed_jobs.yml.signature
  pipelines/main/launch_upload_jobs.yml.signature
  pipelines/scheduled/coverage/coverage.yml.signature
  pipelines/scheduled/launch_signed_jobs.yml.signature
  pipelines/scheduled/launch_upload_jobs.yml.signature
  utilities/macos/update_stdlib_pkgimage_checksums.jl
  utilities/test_julia.sh
  utilities/update_stdlib_pkgimage_checksums.jl
  utilities/upload_julia.sh
Labels: DROP COMMITS BEFORE MERGING

#378 Set up the Kodiak automerge bot on this repo
  .kodiak.toml
Labels: merge me

#322 Update `rr` from 5.5 to 5.7
  utilities/rr/rr_capture.jl
Labels: automerge
